# To run this file, some addresses need to be changed in the project:

# In dktbdiagent/src/main/resources/application.properties
## Change first line:
## from: spring.datasource.url=jdbc:postgresql://localhost:5432/dktbase
## to: spring.datasource.url=jdbc:postgresql://db:5432/dktbase

# In dktrasa/endpoints.yml
## Change:
## from: url: "http://localhost:5055/webhook"
## to: url: "http://action-server:5055/webhook"

# In dktrasa/actions/actions.py
## Change:
## from:
## BDIAGENT_ENDPOINT = "http://localhost:8080/agent/"
## REPORT_ENDPOINT = "http://localhost:8080/report/"
## to:
## BDIAGENT_ENDPOINT = "http://dktbdiagent:8080/agent/"
## REPORT_ENDPOINT = "http://dktbdiagent:8080/report/"

version: '3.8'
services:
  dktrasa:
    user: root
    build:
      context: dktrasa
      args:
        DKT_RASA_AUTH: ${DKT_RASA_AUTH}
    ports:
      - "5005:5005"
    environment:
      - DKT_RASA_AUTH=${DKT_RASA_AUTH}
      - DKT_SERVER_ACTIONS=${DKT_SERVER_ACTIONS}
  action-server:
    build:
      context: dktrasa/actions
    ports:
      - "5055:5055"
    environment:
      - DKT_SERVER_BACKEND=${DKT_SERVER_BACKEND}
  db:
    build:
      context: dktpostgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--dbname=dktbase", "--host=localhost", "--port=5432", "--username=postgres" ]
      timeout: 10s
      interval: 10s
      retries: 10
  dktfrontend:
    build:
      context: dktfrontend/training-system-frontend
      args:
        VUE_APP_DKT_SERVER_BACKEND: ${DKT_SERVER_BACKEND}
        VUE_APP_DKT_SERVER_RASA: ${DKT_SERVER_RASA}
    ports:
      - '5601:5601'
    environment:
      - VUE_APP_DKT_SERVER_BACKEND=${DKT_SERVER_BACKEND}
      - VUE_APP_DKT_SERVER_RASA=${DKT_SERVER_RASA}
  dktbdiagent:
    build:
      context: .
      dockerfile: dktbdiagent/Dockerfile
      args:
        DKT_SECRET: ${DKT_SECRET}
        DKT_SERVER_WEB: ${DKT_SERVER_WEB}
        DKT_RASA_AUTH: ${DKT_RASA_AUTH}
        DKT_SERVER_DB: ${DKT_SERVER_DB}
        DKT_DB_USER: ${DKT_DB_USER}
        DKT_DB_PASSWORD: ${DKT_DB_PASSWORD}
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DKT_SECRET=${DKT_SECRET}
      - DKT_SERVER_WEB=${DKT_SERVER_WEB}
      - DKT_RASA_AUTH=${DKT_RASA_AUTH}
      - DKT_SERVER_DB=${DKT_SERVER_DB}
      - DKT_DB_USER=${DKT_DB_USER}
      - DKT_DB_PASSWORD=${DKT_DB_PASSWORD}
